import LocalizedStrings from 'react-localization';

var strings = new LocalizedStrings({

  en: {
    ADD_DETAILS: 'Add Details',
    Customer_info: "Customer Information:",
    Select_Language: " --- select Language ---",
    Enter_Name: "Enter Name ",
    Enter_Address: "Enter Address",
    Enter_Mobile_NO: "Enter Mobile No",
    Enter_GSt: "Enter Gst-No",
    Product_info: "Product Information",
    ADD_item: "Add item",
    Item: "Item",
    Enter_Item_Name: "Enter Item name",
    Enter_Item_Price: "Enter Item Price",
    Save_Product: "Save Product",
    ClOSE: "Close",
    SAVE: "Save Change",
    BLUESOFT: "BlueSoft",
    A1: "240 - RoyalPlaza",
    A2: "bapasitaram Chock",
    A3: "Jakatnaka,Surat-394130",
    Billed_To: "Billed To",
    Invoice_Number: "Invoice Number",
    Date: "Date Of Issue",
    Invoice_Total: "Invoice Total",
    Product: "Product",
    Cost: "Cost",
    Quentity: "Quentity",
    Amount: "Amount",
    Discount: "Discount",
    Sub_Total: "Sub Total",
    Tax: "Tax",
    Total: "Total",
    Invoice_Terms: "Invoice terms",
    In_Text: "Ex.Please Pay Your invoice by..",
    Amount_Due: "Amount Due(USD)",
  },

  gj: {
    ADD_DETAILS: 'વિગતો ઉમેરો',
    Customer_info: "ગ્રાહક માહિતી:",
    Select_Language: " --- ભાષા પસંદ કરો ---",
    Enter_Name: "નામ દાખલ કરો ",
    Enter_Address: "સરનામું દાખલ કરો",
    Enter_Mobile_NO: "મોબાઇલ નંબર દાખલ કરો",
    Enter_GSt: "Gst-No દાખલ કરો",
    Product_info: "ઉત્પાદન માહિતી",
    ADD_item: "આઇટમ ઉમેરો",
    Item: "વસ્તુ",
    Enter_Item_Name: "આઇટમ નામ દાખલ કરો",
    Enter_Item_Price: "આઇટમ ભાવ દાખલ કરો",
    Save_Product: "ઉત્પાદન સાચવો",
    ClOSE: "બંધ",
    SAVE: "ફેરફાર સાચવો",
    BLUESOFT: "બ્લુસોફ્ટ",
    A1: "240 - રોયલપ્લાઝા",
    A2: "બાપસીતારામ ચોક",
    A3: "જકાતનાકા, સુરત -394,130",
    Billed_To: "બિલ ટુ",
    Invoice_Number: "બીલ નંબર",
    Date: "ઇશ્યુની તારીખ",
    Invoice_Total: "ભરતિયું કુલ",
    Product: "ઉત્પાદન",
    Cost: "કિંમત",
    Quentity: "જથ્થો",
    Amount: "રકમ",
    Discount: "ડિસ્કાઉન્ટ",
    Sub_Total: "પેટા કુલ",
    Tax: "કર",
    Total: "કુલ",
    Invoice_Terms: "ભરતિયું શરતો",
    In_Text: "ભૂતપૂર્વ કૃપા કરીને તમારા ઇન્વોઇસ દ્વારા ચૂકવણી કરો ..",
    Amount_Due: "બાકી રકમ (યુએસડી)",
  },

  hi: {
    ADD_DETAILS: 'विवरण जोड़ें',
    Customer_info: "ग्राहक सूचना:",
    Select_Language: "--- भाषा का चयन करें ---",
    Enter_Name: "नाम दर्ज",
    Enter_Address: "पता लिखिए",
    Enter_Mobile_NO: "मोबाइल नंबर दर्ज करें",
    Enter_GSt: "Gst-No दर्ज करें",
    Product_info: "उत्पाद की जानकारी:",
    ADD_item: "सामान जोडें",
    Item: "आइटम",
    Enter_Item_Name: "आइटम का नाम दर्ज करें",
    Enter_Item_Price: "आइटम मूल्य दर्ज करें",
    Save_Product: "उत्पादों को बचाओ",
    ClOSE: "बंद करे",
    SAVE: "बदलाव सुरक्षित करे",
    BLUESOFT: "ब्लुएसोफट ",
    A1: "240 - रॉयलपलाजा",
    A2: "बापसीताराम चोक",
    A3: "जकातकट्टा, सूरत -394,130",
    Billed_To: "बिल किया गया",
    Invoice_Number: "बीजक संख्या",
    Date: "जारी करने की तारिख",
    Invoice_Total: "कुल बिल",
    Product: "उत्पाद",
    Cost: "लागत",
    Quentity: "मात्रा",
    Amount: "रकम",
    Discount: "छूट",
    Sub_Total: "उप कुल",
    Tax: "कर",
    Total: "संपूर्ण",
    Invoice_Terms: "चालान की शर्तें",
    In_Text: "कृपया अपने चालान का भुगतान करें ।।",
    Amount_Due: "देय राशि (USD)",
  },

});
export default strings;
